### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by philoserf** [ruby-ore/ore#49]
Please add a `CONTRIBUTING.md` see https://help.github.com/articles/setting-guidelines-for-repository-contributors/

It is not clear how to contribute to the project.

**Comment by postmodern** [comment]
are there any questions you'd like answered in a `CONTRIBUTING.md` specifically?

**Comment by philoserf** [comment]
Why yes @postmodern , there are a few. :grin:

1. Are contributions welcome?
2. What does the project want in _Issues_?
3. Are _Pull Requests_ welcome?

I hadn't looked at `ore` in a few years. Then I saw it had awoken. Personally, I'm curious if the current contributors have a direction for the future of `ore` and a desire to accept third-party contributions.

- - - - -

from the Github help document:
> For the repository owner, contribution guidelines are a way to quickly communicate how people should contribute.

> For contributors, these guidelines help them verify that they're submitting well-formed pull requests and opening useful issues.

> For both owners and contributors, contribution guidelines save time and hassle generated by improperly created pull requests or issues that have to be rejected and re-submitted.

**Comment by postmodern** [comment]
Bugs, issues, improvements, feature requests, the usual. If your issue is with a specific template, then probably submit it to the appropriate GitHub repo. Pull Requests to fix minor things are welcomed. Although, I kind of want to rewrite portions of Ore to be more Object Orientated. Even thought about working on writing a generic template/generation library that Ore and other projects with generators could benefit from. Also thought of renaming the project (the whole ore != mine thing bothers me), or turning it into a rubygem plugin.

Despite those things, Ore satisfies my needs to generate new gems just how I want them initially setup.
